# Question 2: 

Question: How many hospitals are located in each state?
#MAKE A CHOROPLETH MAP !!

Load data and libraries to use and preprocessing

```{r}

library(viridis)
library(statebins)
library(datasets)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(maps)

hospitals <- read_csv("https://raw.githubusercontent.com/36-SURE/36-SURE.github.io/main/data/hospitals.csv")

us_states <- map_data("state")

groupedStates <- hospitals |>
  group_by(Facility.State) |>
  summarise(count = n())

groupedStates$region <- tolower(state.name[match(groupedStates$Facility.State, state.abb)])

# View(groupedStates)
mergedData <- left_join(groupedStates, us_states, by = c("region"))
# View(mergedData)

```

Exploratory Data Analysis

```{r}
# finding summary counts 
summaryCounts <- groupedStates |>
  filter(region != "NA") |>
  summary(count)

#find state with the lowest and highest number of hospitals
orderedCounts <- arrange(groupedStates, desc(count))

highestNum <- slice_head(orderedCounts, n = 5)

lowestNum <- orderedCounts |>
  filter(region != "NA") |>
  slice_tail(n=5)



print(summaryCounts)
print(highestNum)
print(lowestNum)

```


create choropleth map

```{r}
usa_count <- mergedData |>
  ggplot(aes(x = long, y = lat, group = group, fill = count)) +
  geom_polygon(color = "black") +
  coord_map("polyconic") +
  scale_fill_viridis_c() +
  labs(
    x = "",
    y = "",
    title = "Hospital Counts by State",
    subtitle = "Data from CORGIS Dataset Project"
  ) +
  scale_y_continuous(labels = NULL) +
  scale_x_continuous(labels = NULL) +
  theme_light() +
  theme(
    text = element_text(family = "serif"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    strip.background = element_blank(),
    plot.title = element_text(hjust = 0.5, face = "bold", size = 18),
    plot.subtitle = element_text(hjust = 0.5, size = 11),
    plot.legend = element_text(size = 12),
    legend.text = element_text(size = 12),
  )

#ggsave("hospital_count.pdf", plot = usa_count, device = "pdf", width = 10, height = 8, path = getwd())
#uncomment if you want to save pdf

```

