Question one, does hospital impact the mortality rate? 

```{r}

library(tidyverse)
library(scales)


hospitals <- read_csv("https://raw.githubusercontent.com/36-SURE/36-SURE.github.io/main/data/hospitals.csv")

#View(hospitals)
str(hospitals)


```

#this filters out unknown and none in our data
#if you want to change the orders on the graph thant change line 18 
```{r}
hospitals_type <- hospitals |> 
  filter(Rating.Mortality != "None", Facility.Type != "Unknown") |> 
  mutate(Rating.Mortality = factor(Rating.Mortality, levels = c("Below", "Same", "Above")),
         Facility.Type = factor(Facility.Type))
         
```



```{r}
# Calculate proportions
mortality_proportion <- hospitals_type |> 
  group_by(Facility.Type, Rating.Mortality) |> 
  summarize(count = n(), .groups = 'drop') |> 
  group_by(Facility.Type) |> 
  mutate(proportion = round(count / sum(count), 2))

mortality_proportion <- mortality_proportion |> 
  mutate(label = scales::percent(proportion, accuracy = 1))

#Stacked bar graph
mortality_proportion |> 
  ggplot(aes(x = Facility.Type, y = proportion, fill = Rating.Mortality)) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(label = label), 
            position = position_stack(vjust = 0.5), 
            size = 4.5, 
            color = "white",
            fontface = "bold") + # Add percentage labels
  scale_fill_viridis_d(option = "D", begin = 0, end = 0.75, direction = 1) + 
  scale_y_continuous(labels = NULL) + # Remove y-axis labels
  labs(title = "Proportion of Mortality Ratings by Hospital Type", 
       subtitle = "Data from CORGIS Dataset Project",
       x = "Hospital Type", 
       y = "Proportion", 
       fill = "Mortality Rating*",
       caption = "*All ratings are compared to the national average") +
  theme_minimal(base_size = 18) +
  theme(
    text = element_text(family = "serif"),
    plot.title = element_text(size = 18, face = "bold"),
    plot.subtitle = element_text(size = 12),
    plot.caption = element_text(size = 12, face = "italic"),
    axis.text = element_text(size = 16),
    axis.title = element_text(size = 16),
  )
```


```{r}
mortality_summary <- hospitals_type |> 
  group_by(Facility.Type, Rating.Mortality) |> 
  summarize(count = n(), 
            .groups = 'drop')

mortality_summary |> 
  ggplot(aes(x = Facility.Type, y = count, fill = Rating.Mortality)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Hospital Type vs Mortality Rate", 
    x = "Hospital Type", 
    y = "Count", 
    fill = "Mortality Rating")

```




